version: "3"

services:

  server:
    build: .
    depends_on:
      - database
    ports: 
      - "3003:3003"

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=photolist
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
